#
# Copyright (c) Mark J. Kilgard, 1996, 1997.
#
# Altered for MacOS 10.14 - davehouse Feb, 2020

LDLIBS= -framework GLUT -framework OpenGL -framework Cocoa -Wno-deprecated
CPPFLAGS = -DGL_SILENCE_DEPRECATION

SRCS = opengl_logo.c def_logo.c
OBJS =	$(SRCS:.c=.o)

opengl_logo : $(OBJS) $(GLUT)
	$(CC) $(LDLIBS) -o $@ $(OBJS) $(LDFLAGS)

include $(COMMONRULES)
