#
# Copyright (c) Mark J. Kilgard, 1996, 1997.
#
# Altered for MacOS 10.14 - davehouse Feb, 2020


LDLIBS= -framework GLUT -framework OpenGL -framework Cocoa -Wno-deprecated
CPPFLAGS = -DGL_SILENCE_DEPRECATION

SRCS =	display.c fileio.c main.c make_face.c muscle.c
OBJS =	$(SRCS:.c=.o)

geoface: $(OBJS) $(GLUT)
	$(CC) $(LDLIBS) -o $@ $(OBJS) $(LDFLAGS)

include $(COMMONRULES)
