# Makefile for Win32

!include <win32.mak>

TOP  = ../../..
SRCS = walker.c

!include "$(TOP)/glutwin32.mak"

# dependencies
walker.exe	: walkviewer.obj models.obj
walker.c	: walker.h
walkviewer.c	: walkviewer.h
